### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by airvb** [marklam/PiTsOff#1]
Bonjour,
I try to install under last Open Elec beta . It failed without any message.

Any idea ?

thanks

**Comment by marklam** [comment]
I've only tested on osmc, but what happened when you installed on openelec - was there a popup to say it failed? Do you know where the kodi logs are written - on osmc you can ssh in and find logs in `~/.kodi/temp` (from memory)

**Comment by airvb** [comment]
Thanks for yr prompt reply .

When i try to install it said to me that the zip stucture isn't correct.

I try de unzip directly in the folder, but i don't know if it is the same for OSMC, but under OPENELEC, the addon folder is mount only in read condition .

Any idea ?

thanks

ps forgive me for my english !:)

**Comment by marklam** [comment]
Hi, I've created a new release after checking line-endings etc.
I downloaded the zip file from GitHub
https://github.com/marklam/PiTsOff/releases/download/v0.2.4/screensaver.pitsoff-0.2.4.zip
and copied it via SMB to a shared folder on the pi, then chose 'install from zip' and it worked OK.
Can you try this new file on your OpenELEC install and see if it works any better? thanks.

ps. Your English is fine!

**Comment by airvb** [comment]
Hello .
Installation is ok now .
I selected ' Pitoff' screen saver  , blank after one minute
The screen passed blank but without switching off the backlight:( 

Confirmed by enter the following cmd in ssh mode,  which is switching off the backlight
echo 1 > /sys/class/backlight/rpi_backlight/bl_power  

i ll tried later with a fresh install of open elec.
thanks for yr help

**Comment by marklam** [comment]
Hi, I checked out openelec - and the difference is that there's no 'sudo' required. I'll see if I can come up with a version that works with / without sudo (maybe I'll just cheat and try doing both :-)

**Comment by marklam** [comment]
v0.2.6 Should work on OpenELEC.

**Comment by airvb** [comment]
Well done , works on OPEN ELEC now !

Thanks you
